// <auto-generated />
namespace Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updateorderexpand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateorderexpand));
        
        string IMigrationMetadata.Id
        {
            get { return "201308311324479_update-order-expand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
