// <auto-generated />
namespace Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addorderchecklog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addorderchecklog));
        
        string IMigrationMetadata.Id
        {
            get { return "201309030944585_add-order-checklog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
