// <auto-generated />
namespace Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changeorderexpand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeorderexpand));
        
        string IMigrationMetadata.Id
        {
            get { return "201309170045377_changeorderexpand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
