// <auto-generated />
namespace Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addorderchecklog1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addorderchecklog1));
        
        string IMigrationMetadata.Id
        {
            get { return "201309030946311_add-order-checklog1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
