// <auto-generated />
namespace Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changestocklog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestocklog));
        
        string IMigrationMetadata.Id
        {
            get { return "201309031313276_change-stocklog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
